:PROPERTIES:
:ID:       ef0e40b9-e2eb-4db8-958e-4e6080cbc710
:END:
#+title: Guru Ashtakam
#+STARTUP: content
#+date : 2022-12-02
#+filetags: :ancient:sanskrit:ashtakam:

* Guru Ashtakam
    :PROPERTIES:
    :CUSTOM_ID: guru-ashtakam
    :style: font-family: Roboto Condensed; color: white; --darkreader-inline-color: #e8e6e3;
    :darkreader-inline-color:
    :END:

[[https://shlokam.org/wp-content/uploads/2020/11/Guru-Ashtakam-audio.mp3]]


*शरीरं सुरूपं तथा वा कलत्रं यशश्र्चारु चित्रं धनं मेरुतुल्यं |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||1|*


*कलत्रं धनं पुत्रपौत्रादि सर्वं गृहं बान्धवाः सर्वमेतद्धि जातम् |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||2||*

Wife, wealth, sons, grandsons and all such; home and kindred; all these things maybe there; yet if one's mind be not centered upon the lotus feet of the Guru, what then, what then, what then?


*षडङ्गादिवेदो मुखे शास्त्रविद्या कवित्वादि गद्यं सुपद्यं करोति |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं || 3||*

The Vedas with their six limbs and the knowledge of all sciences may be on one's lips; one may possess the poetic gift and may compose fine prose and poetry; yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?


*विदेशेषु मान्यः स्वदेशेषु धन्यः सदाचारवृत्तेषु मत्तो न चान्यः |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||4||*

“I am honoured in other lands and I am prosperous in my homeland; in the paths of righteous conduct there is none who surpasses me”, thus one may think; yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?

*क्षमामण्डले भूपभूपालवृन्दैः सदासेवितं यस्य पादारविन्दं |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||5||*

One may be constantly extolled and one's presence highly honoured by hosts of emperors and rulers of this world; yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?


*यशो मे गतं दिक्षु दानप्रतापा जगद्वस्तु सर्वं करे यत्प्रसादात् |*
गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं || 6||

“My repute has travelled in all directions through my philanthropy and prowess; all the things of this world are in my hands as rewards for my virtues”, yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?


*न भोगे न योगे न वा वाजिराजौ न कान्तामुखे नैव वित्तेषु चित्तं |*
गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||7||

The mind may have turned away from external delights through dispassion and from attainments like Yoga and meditation, possessions like horses and the like, the enchanting face of the beloved, in short, the entire wealth of the earth; yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?


*अरण्ये न वा स्वस्य गेहे न कार्ये न देहे मनो वर्तते मे त्वनर्घ्ये |*
*गुरोरङ्घ्रिपद्मे मनश्र्चेन लग्नं ततः किं ततः किं ततः किं ततः किं ||8||*

The mind may have lost its charm to live in forests, and likewise in the house; may have lost all desire to achieve whatever; even the concern for the body's welfare may have been outlived; yet if one's mind be not centred upon the lotus feet of the Guru, what then, what then, what then?

* Description

Guru Ashtakam beautifully exemplifies the necessity of a Guru, beseeching the spiritual seeker to bow down to the Lotus Feet of the Guru. Composed by Sri Adi Shankaracharya. GuruAshtakam is an octet in the praise of spiritual Guru, composed by Adi Sankaracharya. Originally, Adi Shankara has written this in praise of his Guru Govinda Pada. He emphasizes that without deep devotion to the spiritual teacher, all our attainments are meaningless.
In Hinduism, a Guru is a spiritual teacher who imparts the higher knowledge of the Vedas and the way of achieving liberation (enlightenment). But mere study of books cannot make one a Guru. One who has studied the Vedas, and who has direct knowledge of Atman (soul) through self-realization can only be enrolled as a Guru. A Guru is knowledgeable, self-realized, liberated, chaste, virtuous, austere, truthful, detached, free from lust and delusion, and dedicated and devoted to God. *A Guru is the knower of Brahman.* A Guru is God in human form. The words of a Guru are like the words of God.

[[https://shlokam.org/gurubrahma/][A popular Hindu prayer declares]], “The Guru is Brahma, the Guru is Vishnu, the Guru is Shiva, the Guru is verily the Supreme Absolute itself. To that Guru, I offer my salutations.”

Paying respects to a Guru, touching the feet of a Guru, serving the Guru and taking care of his personal needs, praising and appreciating a Guru, seeking the blessings of a Guru, remembering and meditating on the name of a Guru, are the parts of Hindu spiritual traditions. But it doesn't insist that everyone should have a Guru in physical form. In Hinduism, there is a provision to consider a sacred scripture, a deity or our very Self as our guide and Guru and develop a mental and intuitive connection with them. With the help of concentration, austerities and self-purification, we can strengthen our faith in our personal Guru of the subtle realm and seek his help either to introduce us to a real Guru, or lead us towards light, knowledge and immortality.

* Glory of a Guru
    :PROPERTIES:
    :CUSTOM_ID: glory-of-a-guru
    :END:
According to the Vedas, Lord Vishnu imparted teachings to the sages in ancient times. Starting from the beginning, Lord Vishnu taught Lord Brahma, who in turn taught Sage Vyasa, who in turn taught Sage Shuka; a succession of Gurus and disciples has proceeded down through the ages through Shri Shankaracharya to the present. A Guru is absolutely necessary for every aspirant in the spiritual path. God is the goal, whereas Guru is the path.

All great ones had their teachers. All the sages, saints, prophets, world-teachers, incarnations, great men, however great they might have been, had their own Gurus. Shvetaketu learnt the nature of Truth from Uddalaka, Maitreyi from Yagnavalkya, Bhirgu from Varuna, Narada from Sanatkumara, Nachiketas from Yama, Indra from Prajapati; and several others humbly went to the wise ones, observed strict brahmacharya, practiced rigorous discipline and learnt the science of God from them. Even the incarnation of Lord himself, like Lord Krishna, sat at the feet of his Guru Sandeepani. Lord Rama had Guru Vasishtha, Lord Hanuman had Guru Surya (the Sun God). The Devas (celestial beings) have Brihaspati as their Guru, and even the greatest among the divine beings sat at the feet of Guru Dakshinamurti.

The scriptures are like a forest. There are ambiguous passages. There are passages that are apparently contradictory. There are passages that have esoteric meanings, diverse significance, and hidden explanations. There are cross-references. One is in need of a Guru or a preceptor who will explain to him the right meaning, who will remove doubts and ambiguities, and who will place before him the essence of the teachings.
